services:
  - type: web
    name: trialatportfolio
    env: node
    rootDir: .
    installCommand: npm install
    buildCommand: npm run build
    startCommand: serve -s build
    envVars:
      - key: NODE_VERSION
        value: 18
